apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
      
      
kubectl apply -f mysql-configmap.yml
kubectl apply -f mysql-admin-secrets.yml
kubectl apply -f mysql-user-secrets.yml
kubectl apply -f mysql-pv.yml
kubectl apply -f mysql-deployment.yml      
